### ISSUE TITLE
README does not match implementation

### ISSUE THREAD

**Issue by codenamegary** [ajbdev/cronlingo#4]
The README shows `CronLingo::fromExpression("string")` as the parser method, looks like the actual code has a `CronLingo::cron("string")` method.

I'll submit a couple of patches, can't quite tell which method name you prefer. `fromExpression` seems pretty reasonable though, conveys the true intention of the method. `cron` is a little vague. Could also be `parse` or whatever.

PS - I like it! :)

**Comment by ajbdev** [comment]
Woops. I think I intended to make that change but didn't follow through. Yeah - if you want to patch in fromExpression I'll accept it right away. Thanks for the feedback, glad you like it!

**Comment by ajbdev** [comment]
Thank you!
